from collections import OrderedDict

fiats = ["AED", "AFN", "AMD", "ARS", "AUD", "AZN", "BDT", "BGN", "BHD", "BIF", "BND", "BOB", "BRL", "CAD", "CHF", "CLP",
         "CNY", "COP", "CRC", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ETB", "EUR", "GBP", "GEL", "GHS", "GNF", "GTQ",
         "HKD", "HNL", "HRK", "HUF", "IDR", "INR", "ISK", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KWD", "KZT", "LAK",
         "LBP", "LKR",
         "LYD", "MAD", "MDL", "MGA", "MMK", "MNT", "MOP", "MXN", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN",
         "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SCR", "SDG", "SEK", "THB", "TJS",
         "TMT", "TND",
         "TRY", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VES", "VND", "XAF", "XOF", "YER", "ZAR"]

namesPaysend = {
    "DZD": "algeria",
    "EUR": "spain",
    "ARS": "argentina",
    "AMD": "armenia",
    "AUD": "australia",
    "AZN": "azerbaijan",
    "BDT": "bangladesh",
    "BZD": "belize",
    "XOF": "togo",
    "BTN": "bhutan",
    "BOB": "bolivia",
    "BRL": "brazil",
    "BGN": "bulgaria",
    "BIF": "burundi",
    "XAF": "cameroon",
    "CAD": "canada",
    "USD": "usa",
    "CLP": "chile",
    "CNY": "china",
    "COP": "colombia",
    "CRC": "costa-rica",
    "CZK": "czech-republic",
    "DKK": "denmark",
    "DOP": "dominican-republic",
    "EGP": "egypt",
    "ETB": "ethiopia",
    "GMD": "gambia",
    "GEL": "georgia",
    "GHS": "ghana",
    "GTQ": "guatemala",
    "GNF": "guinea",
    "GYD": "guyana",
    "HTG": "haiti",
    "HNL": "honduras",
    "HKD": "hong-kong",
    "HUF": "hungary",
    "INR": "india",
    "IDR": "indonesia",
    "ILS": "israel",
    "JMD": "jamaica",
    "JPY": "japan",
    "JOD": "jordan",
    "KZT": "kazakhstan",
    "KES": "kenya",
    "KWD": "kuwait",
    "KGS": "kyrgyzstan",
    "MGA": "madagascar",
    "MWK": "malawi",
    "MYR": "malaysia",
    "MRU": "mauritania",
    "MXN": "mexico",
    "MDL": "moldova",
    "MAD": "morocco",
    "MZN": "mozambique",
    "NAD": "namibia",
    "NPR": "nepal",
    "NZD": "new-zealand",
    "NOK": "norway",
    "PKR": "pakistan",
    "PYG": "paraguay",
    "PEN": "peru",
    "PHP": "philippines",
    "PLN": "poland",
    "QAR": "qatar",
    "RON": "romania",
    "RWF": "rwanda",
    "SAR": "saudi-arabia",
    "SLE": "sierraleone",
    "SGD": "singapore",
    "ZAR": "sar",
    "KRW": "south-korea",
    "LKR": "sri-lanka",
    "SEK": "sweden",
    "CHF": "switzerland",
    "TJS": "tajikistan",
    "TZS": "tanzania",
    "THB": "thailand",
    "TRY": "turkey",
    "AED": "uae",
    "UGX": "uganda",
    "UAH": "ukraine",
    "GBP": "united-kingdom",
    "UYU": "uruguay",
    "UZS": "uzbekistan",
    "VND": "vietnam",
    "ZMW": "zambia",
}

idsPaysend = {
    "algeria": "12",
    "andorra": "20",
    "argentina": "32",
    "armenia": "51",
    "australia": "36",
    "austria": "40",
    "azerbaijan": "944",
    "bangladesh": "50",
    "belgium": "56",
    "belize": "84",
    "benin": "204",
    "bhutan": "64",
    "bolivia": "68",
    "brazil": "76",
    "bulgaria": "100",
    "burundi": "108",
    "cameroon": "120",
    "canada": "124",
    "cape-verde": "132",
    "chile": "152",
    "china": "156",
    "colombia": "170",
    "costa-rica": "188",
    "cyprus": "196",
    "czech-republic": "203",
    "denmark": "208",
    "djibouti": "262",
    "dominica": "212",
    "dominican-republic": "214",
    "egypt": "818",
    "el-salvador": "222",
    "estonia": "233",
    "ethiopia": "231",
    "fiji": "242",
    "finland": "246",
    "france": "250",
    "gambia": "270",
    "georgia": "981",
    "germany": "276",
    "ghana": "288",
    "greece": "300",
    "guatemala": "320",
    "guinea": "324",
    "guinea-bissau": "624",
    "guyana": "328",
    "haiti": "332",
    "honduras": "340",
    "hong-kong": "344",
    "hungary": "348",
    "iceland": "352",
    "india": "356",
    "indonesia": "360",
    "ireland": "372",
    "israel": "376",
    "italy": "380",
    "jamaica": "388",
    "japan": "392",
    "jordan": "400",
    "kazakhstan": "398",
    "kenya": "404",
    "kuwait": "414",
    "kyrgyzstan": "417",
    "latvia": "428",
    "liechtenstein": "438",
    "lithuania": "440",
    "luxembourg": "442",
    "madagascar": "450",
    "malawi": "454",
    "malaysia": "458",
    "malta": "470",
    "mauritania": "478",
    "mauritius": "480",
    "mexico": "484",
    "moldova": "498",
    "morocco": "504",
    "mozambique": "508",
    "namibia": "516",
    "nepal": "524",
    "netherlands": "528",
    "new-zealand": "554",
    "niger": "562",
    "norway": "578",
    "pakistan": "586",
    "paraguay": "600",
    "peru": "604",
    "philippines": "608",
    "poland": "616",
    "portugal": "620",
    "qatar": "634",
    "romania": "642",
    "rwanda": "646",
    "san-marino": "674",
    "saudi-arabia": "682",
    "senegal": "686",
    "sierraleone": "694",
    "singapore": "702",
    "slovakia": "703",
    "slovenia": "705",
    "sar": "710",
    "south-korea": "410",
    "spain": "724",
    "sri-lanka": "144",
    "sweden": "752",
    "switzerland": "756",
    "tajikistan": "762",
    "tanzania": "834",
    "thailand": "764",
    "togo": "768",
    "turkey": "949",
    "uae": "784",
    "uganda": "800",
    "ukraine": "804",
    "united-kingdom": "826",
    "uruguay": "858",
    "usa": "840",
    "uzbekistan": "860",
    "vietnam": "704",
    "zambia": "894",
}

names = ["Дирхам ОАЭ", "Афганский афгани", "Армянский драм", "Аргентинское песо", "Австралийский доллар",
         "Азербайджанский манат", "Бангладешская така", "Болгарский лев", "Бахрейнский динар", "Бурундийский франк",
         "Брунейский доллар",
         "Боливийский боливиано", "Бразильский реал", "Канадский доллар", "Швейцарский франк", "Чилийское песо",
         "Китайский юань", "Колумбийское песо", "Коста-риканский колон", "Чешская крона", "Франк Джибути",
         "Датская крона",
         "Доминиканское песо", "Алжирский динар", "Египетский фунт", "Эфиопский быр", "Евро", "Фунт стерлингов",
         "Грузинский лари", "Ганский седи", "Гвинейский франк", "Гватемальский кетсаль", "Гонконгский доллар",
         "Гондурасская лемпира",
         "Хорватская куна", "Венгерский форинт",
         "Индонезийская рупия", "Индийская рупия", "Исландская крона", "Иорданский динар", "Японская иена",
         "Кенийский шиллинг", "Киргизский сом", "Камбоджийский риель", "Коморский франк", "Кувейтский динар",
         "Казахстанский тенге",
         "Лаосский кип", "Ливанский фунт", "Шри-ланкийская рупия", "Ливийский динар", "Марокканский дирхам",
         "Молдавский лей", "Малагасийский ариари", "Мьянманский кьят", "Монгольский тугрик", "Патака Макао",
         "Мексиканское песо",
         "Нигерийская найра", "Никарагуанская кордоба", "Норвежская крона", "Непальская рупия", "Новозеландский доллар",
         "Оманский риал", "Панамский бальбоа", "Перуанский соль", "Кина", "Филиппинское песо", "Пакистанская рупия",
         "Польский злотый", "Парагвайский гуарани", "Катарский риал",
         "Румынский лей", "Сербский динар", "Российский рубль", "Франк Руанды", "Саудовский риял", "Сейшельская рупия",
         "Суданский фунт", "Шведская крона", "Тайский бат", "Таджикский сомони", "Туркменский манат", "Тунисский динар",
         "Турецкая лира", "Новый тайваньский доллар", "Танзанийский шиллинг", "Украинская гривна",
         "Угандийский шиллинг", "Доллар США", "Уругвайское песо", "Узбекский сум", "Венесуэльский боливар",
         "Вьетнамский донг",
         "Центральноафриканский франк КФА", "Западноафриканский франк КФА", "Йеменский риал", "Южноафриканский рэнд"]

headers = {
    "accept-language": "ru",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 "
                  "Safari/537.36 "
}

headersPaysend = {
    "User-Agent": "PostmanRuntime/7.30.0",
    "Accept": "*/*",
    "Postman-Token": "39ced7f2-ea97-45e7-bd55-0cb62b2d7745",
    "Host": "paysend.com",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Cookie": "SESSION=NGMzODgyMTQtODY3Yi00Mjc1LTg3N2EtMTRjN2YzNGYxZDRh",
    "Content-Length": "0",
}